# Generated by Django 5.1.3 on 2024-11-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.FileField(blank=True, upload_to='service_logos/'),
        ),
    ]
